---

- hosts: localhost
  connection: local

  tasks:
    - homebrew_tap:
        name: homebrew/cask-fonts     
    - name: install node
      homebrew: name={{item}} state=latest
      with_items:
        - node
    - name: install tree
      homebrew: name={{item}} state=latest
      with_items:
        - tree
    - name: install dev tools
      homebrew: name={{item}} state=latest
      with_items:
        - homebrew/core/make
        - mkcert
        - nss
        - mysql-client
        - automake
        - awscli
        - composer
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        #- adobe-acrobat # 2016/09/20 - Download failed on Cask 'adobe-bridge-cc' with message: Download failed: http://trials3.adobe.com/AdobeProducts/KBRG/6/osx10/Bridge_6_LS20.dmg
        #- adobe-bridge-cc
        #- adobe-illustrator-cc
        #- adobe-indesign-cc
        #- adobe-photoshop-cc
        - adobe-acrobat-reader
        #- bartender
        # browsers
        - firefox
        - google-chrome
        # code
        - atom
        # communication
        - skype
        - slack
        # diff
        - diffmerge
        # gitx - rowanj-gitx swapped for gitx - 2016-11=03 not compatible w/ osX 10.12.
        - rowanj-gitx
        - sourcetree
        # cross-computer functionality
        #- airdisplay
        - airserver
        - synergy
        # development
        - docker
        - kitematic
        #- mamp
        # happy eyes
        - flux
        # java
        #- java
        # music
        #- amazon-music
        # office
        # - microsoft-office #2016-09-20 Download failed on Cask 'microsoft-office' with message: Download failed: https://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/OfficeMac/Microsoft_Office_2016_15.26.0_160910_Installer.pkg
        # sftp
        #- transmit
        # tools
        - onyx
        # quicklook plugins
        - animated-gif-quicklook
        #- qlcolorcode
        #- qlstephen
        #- qlmarkdown
        #- quicklook-json
        #- qlprettypatch
        #- quicklook-csv
        #- betterzip
        #- webpquicklook
        #misc
        #- dropbox
        #- hazel
        - istat-menus
        #- kaleidoscope
        #- sonos
        #- tower
        #- superduper
        #- keepingyouawake
        #- omnigraffle
        #- sketch
        - suspicious-package


    - name: create ssh directory
      become: yes
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh
    - name: personal ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh_config
    - name: personal ssh config in another location
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh/ssh_config
    #### Uncomment the following lines on your username.yml file, replacing 'roderik' with your username to add to sudoers without password
    #- name: add to sudoers without password
    #  become: yes
    #  lineinfile: >
    #    dest=/etc/sudoers
    #    regexp="{{ item.regexp }}"
    #    line="{{ item.line }}"
    #    state=present
    #    create=true
    #  with_items:
    #    - { regexp: '^roderik', line: 'roderik ALL=(ALL) NOPASSWD: ALL' }

  roles:
    - profile-all
    - profile-developer

  vars:
    #### Uncomment and Update personal information here
    #- computername: 
    #- git_user_name: 
    #- git_user_email: 
    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: integer
        value: 1
      - domain: 'com.apple.dock'
        key: 'show-process-indicators'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'orientation'
        type: string
        value: bottom
      - domain: 'NSGlobalDomain'
        key: 'NSTableViewDefaultSizeMode'
        type: integer
        value: 1
      - domain: 'com.apple.screencapture'
        key: 'type'
        type: string
        value: png
      - domain: 'NSGlobalDomain'
        key: 'KeyRepeat'
        type: integer
        value: 2
      - domain: 'NSGlobalDomain'
        key: 'InitialKeyRepeat'
        type: integer
        value: 15
      - domain: 'com.apple.menuextra.clock'
        key: 'DateFormat'
        type: string
        value: EEE MMM d  HH:mm
      - domain: 'com.apple.menuextra.battery'
        key: 'ShowPercent'
        type: string
        value: 'YES'
      - domain: 'com.apple.finder'
        key: 'FXPreferredViewStyle'
        type: string
        value: "clmv"
      # reverse horizontal scroll #requires a restart or kill / restart cfprefsd
      - domain: 'NSGlobalDomain'
        key: 'com.apple.swipescrolldirection'
        type: boolean
        value: false
      # show hidden files  defaults write com.apple.finder AppleShowAllFiles YES
      # TODO add killall Finder /System/Library/CoreServices/Finder.app
      - domain: 'com.apple.finder'
        key: 'AppleShowAllFiles'
        type: boolean
        value: true
      # finder- search "When performing a search, search the current folder by default"
      - domain: 'com.apple.finder'
        key: 'FXDefaultSearchScope'
        type: string
        value: "SCcf"
      # Use Keyboard - Use all F1, F@, etc. keys as standard functions keys defaults write -g com.apple.keyboard.fnState -bool true
      - domain: 'NSGlobalDomain'
        key: 'com.apple.keyboard.fnState'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'NSNavPanelExpandedStateForSaveMode'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'PMPrintingExpandedStateForPrint'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'tilesize'
        type: float
        value: 32
      - domain: 'com.apple.dock'
        key: 'autohide-time-modifier'
        type: int
        value: 0
      - domain: 'com.apple.dock'
        key: 'autohide-delay'
        type: int
        value: 0
      - domain: 'NSGlobalDomain'
        key: 'NSQuitAlwaysKeepsWindows'
        type: boolean
        value: false
      - domain: 'com.apple.desktopservices'
        key: 'DSDontWriteNetworkStores'
        type: boolean
        value: false
      - domain: 'com.apple.print.PrintingPrefs'
        key: 'Quit When Finished'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeInternalDebugMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeDevelopMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'WebKitDeveloperExtrasEnabledPreferenceKey'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'WebKitDeveloperExtras'
        type: boolean
        value: true
