---
- hosts: localhost
  connection: local

  tasks:
    - name: install more personal cask applications
      homebrew_cask: name={{item}} state=present
      ignore_errors: yes
      with_items:
        # rdp
        - microsoft-remote-desktop-beta

# chain vid.yml but set custom variables: computername, git user/email; and update sudo
- include: vid.yml computername=Vids-MacBook-Pro git_user_name="vid" git_user_email="vid@paloalto.com" php_version="72"
